repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.1.1
  hooks:
  - id: trailing-whitespace
  - id: flake8
    args:
    # 79 chars is too strict and we don't have 80-char terminals nowadays,
    # 160 chars is too much since it doesn't let us use split view efficiently:
    - --max-line-length=120
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: name-tests-test
    args: [--django]
  - id: debug-statements
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
    include: .mention-bot
  - id: pretty-format-json
  - id: check-symlinks
  - id: check-yaml
  - id: detect-private-key
  - id: requirements-txt-fixer

- repo: git://github.com/Lucas-C/pre-commit-hooks
  sha: v1.1.1
  hooks:
  - id: remove-tabs

- repo: git://github.com/detailyang/pre-commit-shell
  sha: 1.0.2
  hooks:
  - id: shell-lint
