language: python
python:
- 3.5
- &mainstream_python 3.6
- 3.6-dev
- nightly

cache: pip

before_install:
- pip install -U pip setuptools wheel
install:
- pip install .
script:
- python -m unittest discover -s tests -vv

jobs:
  fast_finish: true

  include:
  - stage: &lint_stage_name lint
    python: *mainstream_python
    install:
    - pip install pre-commit
    script:
    - pre-commit run --all-files

  - stage: &deploy_stage_name deploy
    python: *mainstream_python
    install: []
    script: []
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
        python: *mainstream_python
      user: rrader
      password:
        secure: JPQswZqvgD1lHg5Yv0dqiIITOaQWdn52klv0IWJtLFi/i5MADdp2Gq3WPr4rbuF92lLMbQW012DXRkl7TpzNtMout7kkWOepPIK/EB7I/ZLtKfr2gYHL0m/ZAZmYSDRT+TaqJhfycNvJVQHHFwnamfo+43SzZU7CRITV7nLSQs2rKhsJf2UNUytFYE9BOnG6FyOyu8qX2Qq4ZYgMvesJ0TvTsfpuscNyS8Sn4fNsT/hDMf4nplsEhw40BDovNlx6+QjAgOEnzwYMXLXTdtiD2qk/EZqKqho33tqx8DAgL9GCtN2LVbs8H5CdFTvmZ1akaez9fndx5MJPs4k+mxiva+sdecUW7t1/6wy/Z+B8ibIDj4o2m54IwpP1NXcoA5xoCflSVyJAMQMqBJXmAXFNI188c4wXgirQRbn+l6AvFlFiBcqcSH2g205obMTFENuMtAXHLw1wWucDnfoRKctxcv7qOCYu7SPcV2o3/tbs1LqKywtRNTmZIZveqjtqAQw3RCPzNJ/7vwTdx0QA5W8CbybYUdxdX8tzuCOBRmEK/CkmvJLpQXjDLMRgdazzvbdNSpIshh15PGi9JSP7rOE/XfW1td/lK0XlrCasm11CkmWYjAftUwzUmqJOMoYpn8OO72dy1bd1WTOcsr4Adud07fVU1P7SJiuPfBixPFzzSJA=
      distributions: release

stages:
- *lint_stage_name
- test
- name: *deploy_stage_name
  if: tag IS present
